image: alpine/latest
packages:
  - hugo
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://git.sr.ht/~sbaildon/baildon.co
environment:
  site: baildon.co
tasks:
- package: |
    cd $site
    hugo
    tar -C public -cvz . > ../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/sbaildon.srht.site -Fcontent=@site.tar.gz
