image: nixos/20.09
packages:
  - nixos.zola
  - nixos.gnumake
sources:
  - https://git.sr.ht/~sbaildon/baildon.co
secrets:
  - 1f1a500b-dc44-4cf8-a166-9193885fe841
environment:
  project: baildon.co
tasks:
  - build: |
      cd ${project}
      make
  - upload: |
      cd ${project}
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      rsync -r public/ deploy@baildon.co:/var/www/baildon.co/
